spring:

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/web
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: oauth

server:
  servlet:
    encoding:
      force-response: true
