spring:

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  profiles:
    include: oauth
    active: prod

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        use-new-id-generate-mappings: false
        show_sql: false
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

server:
  servlet:
    encoding:
      force-response: true